### ISSUE TITLE
Not working anymore :(

### ISSUE THREAD

**Issue by chaoscreater** [normalian/My-Azure-Portal-ChromeExtension#2]
Hi,

The highlight empty resource group feature doesn't work anymore, seems like it's incompatible with the latest Azure update.

**Comment by normalian** [comment]
Thanks so much for letting me know and sorry for delaying to be aware of this. I will fix the issue as soon as possible.

**Comment by normalian** [comment]
Hi chaoscreater, I checked the availability of highlight empty resource group feature, but it does not work well on new version Chrome extension. New version of Chrome extension does not allow to webhook, so we cannot leverage accesstoken. Unfortunately, there is no other way to delete the feature.

**Comment by chaoscreater** [comment]
> Hi chaoscreater, I checked the availability of highlight empty resource group feature, but it does not work well on new version Chrome extension. New version of Chrome extension does not allow to webhook, so we cannot leverage accesstoken. Unfortunately, there is no other way to delete the feature.

Would it be possible for you to modify it so that we can enter the access token manually? I know how to get the access token myself.

Alternatively, can you create a version that is able to be sideloaded? If it is a sideloaded version, then it doesn't need to be installed from the Chrome store. The sideloaded version can just be a developer version without any of the limitations.

**Comment by normalian** [comment]
Thanks for

**Comment by normalian** [comment]
Thanks for good suggestion. It's possible to update my extension like you mentioned if you will directly put your accesstoken for yourself. Let me have a couple of weeks. I will update it.

**Comment by normalian** [comment]
It might be possible to update my extension like you mentions. Let me check the possibility.

**Comment by normalian** [comment]
Thanks so much for your great suggestion. It might be possible to update my extension by putting accesstoken directly. Let me check the possibility.

**Comment by normalian** [comment]
I updated my Chrome extension, then the extension is under review by Google. I believe it will be published shortly, but please note that AccessToken expires in 30 to 60 minutes. 
https://learn.microsoft.com/en-us/answers/questions/843346/how-to-change-token-expiration-time-in-azure-porta

**Comment by chaoscreater** [comment]
Does the new version highlight empty resource groups?

Also, this is the Chrome extension I'm using to get the bearer access token:
https://chrome.google.com/webstore/detail/azure-authorization-heade/ifmjcgakbgnpnppgijcikhpolljgdmlc

**Comment by chaoscreater** [comment]
I've just tried the latest 0.3.1 version and it still doesn't highlight the resource group. It used to do this without issues. I've added my access token and saved it and refreshed Azure Portal. No highlight on the empty resource groups.

**Comment by normalian** [comment]
Thanks so much for sharing your feedback. I will check and test again in my env

**Comment by normalian** [comment]
Thanks so much for sharing your feedback! I believe the latest 0.3.1 version should work well. I doubt that your suggested Chrome extension still works well, because the code uses prohibited one, which I also used it in my old version. I use "az account get-access-token" command and pick up AccessToken from it, then my highlight feature works well in my env.

Please share console log from F12 developer tool on Chrome if my Extension still not works well. My extension puts error log for AccessToken issues on developer tool console.

**Comment by normalian** [comment]
Please note AccessToken is required to refresh within 30-60min.

**Comment by chaoscreater** [comment]
Thanks, I got it working by using `az account get-access-token` like you suggested. The Chrome extension I was using to get the bearer token has almost the same token, but it's much shorter. The token generated from the Chrome extension still works for Azure REST API, so I'm not sure why that didn't work for your extension. Anyway, it works now so that's good. Thanks for your help!

**Comment by normalian** [comment]
Thanks for your prompt checking. I should update README how to enable highlight feature. Thanks again for your collaboration, chaoscreater!

**Comment by chaoscreater** [comment]
For anyone interested, I found another extension that you shows empty resource groups without using access token. You can sideload the extension in any Chromium based browsers.

https://github.com/AKTheKnight/AzurePortalExtension/releases

![image](https://github.com/normalian/My-Azure-Portal-ChromeExtension/assets/18227319/e1785a73-3c1d-41e6-a86c-3c1653161c0d)

**Comment by normalian** [comment]
I checked code of the extension. The logic is completely same with previous version of my extension, so the extension cannot update anymore. I guess the extension might not be available soon if Google would change their restriction strictly.
